import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "doula",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const localeParams = await params;
  const locale = localeParams.locale as "en" | "he";
  const isRTL = locale === "en";
  return (
    <div lang={locale} dir={!isRTL ? "rtl" : "ltr"}>
      {children}
    </div>
  );
}
